# Generated by Django 3.1.7 on 2021-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210313_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='toys',
            field=models.ManyToManyField(blank=True, to='main_app.Toy'),
        ),
    ]
